### ISSUE TITLE
是否可以支持多路？

### ISSUE THREAD

**Issue by woshizhangcheng** [pengtougu/Push-Streaming#1]
你好，请问一下该代码是否支持多路实时显示

**Comment by ppogg** [comment]
是的，这是可以的，但单芯片多路并行势必会造成io占用，间接造成性能严重下降，如果你是准备生产落地的话，并不推荐多路检测，本身核已经不太够用了，如果你是准备拿你的芯片进行单纯的视频推拉流，不包含检测部分，那么多路并行是没问题的~
